Removed FTB because it is no longer in Prism Launcher
PrismLauncher/prismlauncher.org pull request #323
Opened 2023-07-13 12:01 UTC by Onako2

https://github.com/PrismLauncher/PrismLauncher/pull/1040 < PR that removed this feature

2023-07-13 12:08 UTC, Onako2 commented
> I recognise you, I don't know where from lol.
> 
> There's also https://prismlauncher.org/wiki/help-pages/ftb-platform/

Ok, I'll add it..

2023-07-13 12:10 UTC, Onako2 commented
> I recognise you, I don't know where from lol.
> 
> There's also https://prismlauncher.org/wiki/help-pages/ftb-platform/

Only the sceenshot is wrong. FTB Legacy still exists

2023-07-13 12:14 UTC, Trial97 commented
can I count on you when the https://github.com/PrismLauncher/PrismLauncher/issues/235 is done?

2023-07-13 12:28 UTC, Onako2 commented
> can I count on you when the [PrismLauncher/PrismLauncher#235](https://github.com/PrismLauncher/PrismLauncher/issues/235) is done?

Do you mean to readd? Yes

2023-07-13 12:30 UTC, TheKodeToad commented
> > I recognise you, I don't know where from lol.
> > There's also [prismlauncher.org/wiki/help-pages/ftb-platform](https://prismlauncher.org/wiki/help-pages/ftb-platform/)
> 
> Only the sceenshot is wrong. FTB Legacy still exists

Okay, that's fair enough

2023-07-13 13:10 UTC, TheKodeToad commented
For the PR? You can't. I don't think it's a big deal here though!

2023-07-14 05:50 UTC, Onako2 commented
> For the PR? You can't. I don't think it's a big deal here though!

The problem is, that other references aren't in this PR. I could create another PR that contains all other changes

2023-09-10 19:28 UTC, NLZ commented
Isn't it ready to be merged now? What's blocking it?

2023-09-10 20:47 UTC, Onako2 commented
I put it on the wrong branch, thanks for reminding me!

2023-09-28 11:37 UTC, Scrumplex requested changes

2023-09-28 11:37 UTC, Scrumplex commented on src/img/screenshots/NewInstanceFTBDark.png
these screenshots were used on this help page: https://prismlauncher.org/wiki/help-pages/ftb-platform/

make sure to just remove these with the help page

2023-09-28 11:37 UTC, Scrumplex commented on src/img/screenshots/NewInstanceFTBLight.png
ditto

2023-10-31 13:25 UTC, ZekeSmith commented
What do we want to do with this now 8.0 has ftb app import?

2025-09-11 19:07 UTC, GameLord2011 commented
When will this be merged, as it's been more than 2 years since the start of this PR.

2026-04-07 15:52 UTC, GameLord2011 commented
@ZekeZDev and @Onako2, this pr should be closed as FTB modpacks are to be re-added in Prism Launcher 11.

2026-04-07 15:54 UTC, closed without merging