Update install-of-alternatives.md to remove Starlight and some other changes
PrismLauncher/prismlauncher.org pull request #352
Opened 2023-09-22 13:57 UTC by Haskellered

- Remove Starlight
- Replace FO and SO with Additive and Adrenaline, respectively.
- Add note to Rubidium section mentioning Embeddium
- Fix Forge heading size

2023-09-22 19:29 UTC, Madis0 requested changes

2023-09-22 19:29 UTC, Madis0 commented on src/wiki/getting-started/install-of-alternatives.md
> +[Adrenaline](https://modrinth.com/modpack/adrenaline) is a modpack designed with just optimization in mind. Adrenaline has better out-of-the-box performance than Additive, but it doesn't come with th
Why the change?

2023-09-22 19:31 UTC, Imzxhir commented
As much as I respect your decision on removing FO and SO, I don’t think they should be replaced with Adrenaline and Additive.

Don’t get me wrong they are both great modpacks by Devin, but at the same time it seems we are explicitly promoting his packs and saying that his packs provide the best performance. However, each user would have different results on performance, some would get high and some would get worse compared to other packs.

2023-09-22 19:55 UTC, Kichura requested changes
Please do not switch fabulously optimized with additive and adrenaline respectively, there is a clear reason for that.

*(EDIT: We don't want this wiki to make use of alternative packs that look simple on paper but in practice make performance start to vary for other people which zxhir's comment is morely sensable of)*

2023-09-22 20:53 UTC, osfanbuff63 reviewed
Personally, I believe that *removing* FO and SO is a bad idea and would cause much controversy. I also agree that Devin's packs are great packs, but it's not fair to completely replace it after all this time.

To come to a fair compromise, maybe we could have both packs listed in both spots.

*Disclaimer: I am a community moderator for FO, but this comment should be free of that bias, as I also like Devin's modpacks for certain uses.*

2023-09-22 21:18 UTC, Haskellered commented
Quickly quoting ZekeZ from the discord:
![image](https://github.com/PrismLauncher/prismlauncher.org/assets/64590568/6bbda209-a2bc-45ce-bc8a-5c5b64873bdc)
Should I just remove it? Or undo it?

2023-09-23 07:39 UTC, Kichura commented
> Quickly quoting ZekeZ from the discord:
> ![image](https://user-images.githubusercontent.com/64590568/270058966-6bbda209-a2bc-45ce-bc8a-5c5b64873bdc.png)
> Should I just remove it? Or undo it?

Suggest undoing it.

2023-09-23 08:06 UTC, TayouVR commented
I don't really see the point of these changes. Adding Devins packs and Embeddium on top of whats already there, sure!
But removing the existing packs (and mods, including starlight)... I really can't see the benefit. 
Sure; some mods may have incompatibilities with others, but they can still be useful for people with limited hardware capabilities.

If you just added what you did without removing any existing things, I feel like that would be better. Only time where I would remove something would be if A: its discontinued, B: its unstable (which none of the things are, there are only few incompatibilities), C: there are issues with the license or author, or D: it doesn't actually do what it says on the box (e.g. doesn't help with performance, or OF compat)

2023-09-23 09:53 UTC, Haskellered commented
> I don't really see the point of these changes. Adding Devins packs and Embeddium on top of whats already there, sure! But removing the existing packs (and mods, including starlight)... I really can't see the benefit. Sure; some mods may have incompatibilities with others, but they can still be useful for people with limited hardware capabilities.

I'll re-add starlight (as well as the rest), but note that it's only useful for older versions, then.

2023-09-28 22:32 UTC, intergrav commented
Please don't replace SO and FO with my modpacks. I'd much prefer if they were added as alternatives

2023-11-11 19:31 UTC, IThundxr commented
> I don't really see the point of these changes. Adding Devins packs and Embeddium on top of whats already there, sure! But removing the existing packs (and mods, including starlight)... I really can't see the benefit. Sure; some mods may have incompatibilities with others, but they can still be useful for people with limited hardware capabilities.
> 
> If you just added what you did without removing any existing things, I feel like that would be better. Only time where I would remove something would be if A: its discontinued, B: its unstable (which none of the things are, there are only few incompatibilities), C: there are issues with the license or author, or D: it doesn't actually do what it says on the box (e.g. doesn't help with performance, or OF compat)

Startlight is pretty unstable in 1.20, it crashes with almost any mod that does some funny rendering stuff which alot do so it might just be better to remove it since it is infact as said on its mod page, irrelevent now

2024-04-17 21:21 UTC, closed without merging