Update welcome-channel.yaml with new rule.
PrismLauncher/prismlauncher.org pull request #420
Opened 2024-03-20 00:58 UTC by sakecode

This change adds a rule about support for custom clients and cheats. Many of these have custom ways to install them using external installers prism does not work with.

2024-03-20 02:11 UTC, getchoo requested changes
also why not make this a part of rule 6?

2024-03-20 02:11 UTC, getchoo commented on src/welcome-channel.yaml
> +    No support for custom clients & cheats: We do not provide support for issues caused by custom clients, cheats, and external installers (e.g. installer for custom client or cheat) or how to instal
```suggestion
    No support for custom clients & cheats: We do not provide support for issues caused by or the usage of custom clients, cheats, and external installers (e.g. installer for custom client or cheat). Ask their respective developers.
```

2024-03-20 02:14 UTC, sakecode commented
I believe it is better to have a specific rule on the matter to redirect users. I however do like the changes you suggested to this pr.

2024-03-24 14:20 UTC, TheKodeToad commented
I will trying doing what getchoo suggested as we are at the rule limit. I think we now we should just say don't ask for help with cheats because there isn't a lot of room.

(and honestly I think all people need to know regarding custom installers / clients is that they shouldn't be surprised if they don't get a response, it doesn't seem particularly harmful to allow people to ask)

2024-03-24 14:20 UTC, closed without merging