Minify HTML
PrismLauncher/prismlauncher.org pull request #64
Opened 2022-10-21 12:33 UTC by ryanccn

because why not, good for performance in a little way

build-time optimization

2022-11-05 18:43 UTC, Scrumplex requested changes
it's not in package.json?

2022-11-06 11:51 UTC, ryanccn commented
Git 😭

2022-11-06 11:53 UTC, Scrumplex approved these changes

2022-11-06 11:53 UTC, Scrumplex commented
conflicting lol

2022-11-06 12:10 UTC, merged