update `installing-java.md` for prism 9.0+
PrismLauncher/prismlauncher.org pull request #673
Opened 2024-12-04 12:30 UTC by maskersss

2024-12-04 12:48 UTC, TheKodeToad requested changes

2024-12-04 12:48 UTC, TheKodeToad commented on src/wiki/getting-started/installing-java.md
> +In PrismLauncher 9.0+, you can simply let the launcher handle Java automatically on Windows and MacOS by ticking "Autodetect Java versin" and "Auto-download Mojang Java" in:
```suggestion
In PrismLauncher 9.0+, you can simply let the launcher handle Java automatically on Windows, macOS and Linux (not available in all packages) by ticking "Autodetect Java version" and "Auto-download Mojang Java" in:
```

2024-12-04 12:48 UTC, TheKodeToad commented on src/wiki/getting-started/installing-java.md
> +
```suggestion

If the Java downloader is not available for you - which is the case on most Linux packages apart from the official Flatpak and AppImage downloads - manual installation is recommended instead.

```

2024-12-04 13:12 UTC, TheKodeToad commented
I think `Selecting Java`, `Installing Java on Windows`, `Installing Java on macOS`, `Installing Java on Linux` and `Special cases` should be ## instead of # as they should really be subheadings under Manually installing Java

2024-12-04 13:22 UTC, maskersss commented
oh really, you can't have two heading 1's

2024-12-04 13:23 UTC, maskersss commented
is this better?

2024-12-04 14:31 UTC, TheKodeToad commented
> oh really, you can't have two heading 1's

Actually, it's probably best to have # Installing Java right at the top too

2025-01-02 19:22 UTC, getchoo commented on src/wiki/getting-started/installing-java.md
> +In PrismLauncher 9.0+, you can simply let the launcher handle Java automatically on Windows, macOS and Linux (not available in all packages) by ticking "Autodetect Java version" and "Auto-download Mo
```suggestion
In Prism Launcher 9.0+, you can let the launcher handle Java automatically on Windows, macOS and Linux (not available in all packages) by enabling "Autodetect Java version" and "Auto-download Mojang Java" in:
```

2025-01-02 19:22 UTC, getchoo commented on src/wiki/getting-started/installing-java.md
> +This will make Prism automatically download the right Java version depending on your Minecraft version (Java 8 for pre-1.17, Java 17 for 1.17-1.20.4, and Java 21 for 1.20.5+). The rest of this page i
```suggestion
This will make the launcher automatically download the right version of Java for your version of Minecraft (Java 8 for pre-1.17, Java 17 for 1.17-1.20.4, etc.). The rest of this page is going to explain downloading Java manually, and is probably not needed for you.
```

2025-01-02 19:22 UTC, getchoo commented on src/wiki/getting-started/installing-java.md
> +*For 1.16.5 or older* there's a workaround, you need to install an older Java binary. To do that, you should be able to simply use Mojang Java 8u51, see [above](https://prismlauncher.org/wiki/getting
```suggestion
*For 1.16.5 or older* there's a workaround in installing an older Java binary. Mojang Java 8u51 is recommended, and can be automatically installed with the [above](#automatically-installing-java).
```

2025-01-29 15:20 UTC, getchoo approved these changes
LGTM. Thanks and sorry for the wait

2025-01-29 15:20 UTC, getchoo commented on src/wiki/getting-started/installing-java.md
> +> Prism's main screen > Settings (top toolbar) > Java
```suggestion
> Settings (top toolbar) > Java
```
Nit, but this is more in-line with other navigation instructions we have (as we can pretty safely assume most people will be on the main screen)

2025-01-29 15:32 UTC, merged