Update installing-java.md
PrismLauncher/prismlauncher.org pull request #679
Opened 2024-12-17 22:47 UTC by simcye

fix flatpak description to tell you that java isn't manually installed and you must download binaries manually

2024-12-17 23:45 UTC, Lutitious commented on src/wiki/getting-started/installing-java.md
> +The Prism Launcher Flatpak already bundles Java. You must manually download java binaries in Settings > Java > Management tab.
```suggestion
The Prism Launcher Flatpak will download java automatically using the inbuilt java downloader. Using external java is possible but is highly not recommended.
```

2024-12-17 23:45 UTC, Lutitious requested changes

2024-12-17 23:45 UTC, Lutitious commented on src/wiki/getting-started/installing-java.md
> +The Prism Launcher Flatpak already bundles Java. You must manually download java binaries in Settings > Java > Management tab.
```suggestion
The Prism Launcher Flatpak will download java automatically using the inbuilt java downloader. Using external java is possible but is highly not recommended.
```

2026-09-03 20:47 UTC, Scrumplex commented
This is out of date and conflicts with the current codebase. If you are still interested, feel free to rebase and reopen the PR.

2026-09-03 20:47 UTC, closed without merging